# link: https://jonnyhub.com
# author: Jonny.Chang <jonny0624@gmail.com>
name: Auto Publish Blog Site.

# 只有推送到 master 才自动化
on:
  push:
    branches: 
    - master

jobs:
  hugo-publish:
     name: Publish Blog
     runs-on: ubuntu-latest
     steps:
       # 克隆源文件仓库，即存放博客 markdown 文件的仓库
       - name: Clone Original Repo
         uses: actions/checkout@v2
         with:
          submodules: true

       # submodule 子仓库一并同步，不然 submodule 内容会不存在
       - name: Update Original Submodule Repo
         shell: bash
         run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

       # 公开网站是放置在另一个仓库。
       # 克隆 GitHub Pages 仓库，即编译后的网站 html 文件
       - name: Clone GitHub Pages Repo
         uses: actions/checkout@v2
         with:
          # 网站所在的 GitHub 仓库名称
          repository: hellenhub/hellenhub.github.io
          path: public
          ssh-key: ${{ secrets.HELLENHUB_SSH_KEY }}

       # 使用 Hugo Actions
       - name: Setup hugo
         uses: peaceiris/actions-hugo@v2
         with:
           hugo-version: latest
           extended: true

       # Hugo 会产生一堆 min.[hash].* 文件
       - name: Cleanup Old files of public
         working-directory: ./public
         shell: bash
         run: find . -type f -name '*.min.*' -exec rm -f {} \;

       # 始用 Hugo 生成新的网站
       - name: Build new content to public
         working-directory: ./
         run: hugo --minify --gc

       # 部署到新的 GitHub Pages 仓库
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
           publish_dir: ./public
           external_repository: hellenhub/hellenhub.github.io
           publish_branch: master

       # 部署到新的 Gitee Pages 仓库
       - name: Deploy to Gitee Pages
         uses: wearerequired/git-mirror-action@v1
         env:
           # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
           SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
         with:
           # 注意替换为你的 GitHub 源仓库地址
           source-repo: git@github.com:hellenhub/hellenhub.github.io.git
           # 注意替换为你的 Gitee 目标仓库地址
           destination-repo: git@gitee.com:jonnyhub/jonnyhub.git

       - name: Deploy Gitee Pages
         uses: yanglbme/gitee-pages-action@master
         with:
           # 注意替换为你的 Gitee 用户名
           gitee-username: jonnyhub
           # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
           gitee-password: ${{ secrets.GITEE_PASSWORD }}
           # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
           gitee-repo:  jonnyhub/jonnyhub
           # 要部署的分支
           branch: master
           # 要部署的分支上的目录
           directory: ./
           # 是否强制使用 HTTPS
           https: true
